### ISSUE TITLE
Are there any differences when using "predict_raw_text" or not in DrQA model?

### ISSUE THREAD

**Issue by Milozms** [stanfordnlp/coqa-baselines#13]
I saw in README that reading comprehension model sets predict_raw_text=True, while the pipeline model sets predict_raw_text=False. Are there any differences?

**Comment by danqi** [comment]
When predict_raw_text is set to True, it will map the span prediction to the original text (using offsets) and extract the corresponding text for final evaluation (instead of concatenating all words using whitespace). This is a common practice for both SQuAD and CoQA and it usually works slightly better.

**Comment by danqi** [comment]
Oh, for the pipeline model, we need that predicted rationale is tokenized so it can be fed into the seq2seq model directly so we set predict_raw_text=False.
